name: Take 37
description: The Creative Efforts of @MirandaJanell and @ThatFrakkingCat
markdown: redcarpet
highlighter: pygments
timezone: America/Los_Angeles
baseurl: ''
url: http://www.take37.com
paginate: 5
streamurl: http://stream.midnightmovieknights.com/midnight-movie-knights/mmk-64m.mp3
mirandahomelink: https://twitter.com/MirandaJanell
mirandahomelabel: "@MirandaJanell"
kittehhomelink: https://twitter.com/ThatFrakkingCat
kittehhomelabel: "@ThatFrakkingCat"
mmklink: http://www.midnightmovieknights.com/
mmklabel: Midnight Movie Knights
gems:
- jekyll-sitemap
- jekyll-redirect-from
