name: Take 37
description: The creative efforts of @MirandaJanell and @ThatFrakkingCat
markdown: kramdown
highlighter: pygments
timezone: America/Los_Angeles
baseurl: ''
url: http://www.take37.com
paginate: 10
permalink: "/:categories/:year/:month/:title.html"
soundcloudrss: http://feeds.soundcloud.com/users/soundcloud:users:160223565/sounds.rss
gems:
- jekyll-sitemap
- jekyll-redirect-from
